[package]
name = "wall-switch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.44", features = ["derive"] }
walkdir = "2.5.0"
tokio = { version = "1.0", features = ["full"] }
rand = "0.9.2"
